Readd Transf
libsemigroups/libsemigroups_pybind11 pull request #163
Opened 2024-05-21 11:55 UTC by james-d-mitchell

2024-05-21 15:41 UTC, james-d-mitchell commented
I think this is ready to go, @Joseph-Edwards

2024-05-21 15:56 UTC, Joseph-Edwards commented on dev-environment.yml
> +    - lxml
I checked conda-forge and I think we can do this in the interest of minimising conda-pip interactions
```suggestion
dependencies:
  - fmt
  - bs4
  - lxml
  - pip: 
    - accepts
```

2024-05-21 16:02 UTC, Joseph-Edwards commented
Modulo the tests passing (which I assume they will after https://github.com/libsemigroups/libsemigroups/pull/544 is merged) and my minor suggestion above, this looks good to me. That said, I'd like to build and read the docs just to be doubly sure. I'll do this first thing tomorrow morning.

2024-05-22 10:58 UTC, Joseph-Edwards commented on src/transf.cpp
> +   (Perm1([5, 2, 0, 1, 3, 4, 6]), Perm1([0, 1, 2, 3, 4, 5, 6, 7])
```suggestion
   (Perm1([5, 2, 0, 1, 3, 4, 6]), Perm1([0, 1, 2, 3, 4, 5, 6, 7]))
```

2024-05-22 11:46 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   This function returns a newly constructed object of the same type as **f**
```suggestion
   Returns the identity on the same number of points as the degree of *f*.
   This function returns a newly constructed object of the same type as *f*
```

2024-05-22 11:46 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   :complexity: Linear in the degree of **f**.
```suggestion
   :complexity: Linear in the degree of *f*.
```

2024-05-22 11:49 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   This function returns a newly constructed inverse of ``f``. The *inverse* of
```suggestion
   This function returns a newly constructed inverse of *f*. The *inverse* of
```

2024-05-22 11:49 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   :complexity: Linear in the degree of **f**.
```suggestion
   :complexity: Linear in the degree of *f*.
```

2024-05-22 11:50 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   * :math:`i\in \{0, \ldots, n - 1\}` where `n` is the degree of **f**; and
```suggestion
   * :math:`i\in \{0, \ldots, n - 1\}` where `n` is the degree of *f*; and
```

2024-05-22 11:50 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
> +   :complexity: Linear in the degree of **f**.
```suggestion
   :complexity: Linear in the degree of *f*.
```

2024-05-22 11:53 UTC, Joseph-Edwards commented on docs/source/data-structures/elements/transf-helpers.rst
I think we decided on the convention that function parameters to be wrapped in single pair of asterisks like `*f*`. I have made a few suggestions, but I don't think I got all of them.

2024-05-22 11:56 UTC, Joseph-Edwards requested changes
I've read had a more thorough read through the docs now, and it all looks very good to me. I have a few minor comments before I'd be happy to merge.
1. For consistency, should the new pages in the doc have a table of contents as in `Action` and `Knuth-Bendix`?
2. After the signatures of some of the functions, some return types have hyperlinks and some don't. For example, in `PPerm(dom: List[int], img: List[int], deg: int) → StaticPPerm16 | PPerm1 | PPerm2 | PPerm4`, `StaticPPerm16` gets a hyperlink, but the others don't. It's not immediately clear if there's a nice fix for this (or if a nice fix is even necessary), but it would be nice to do if there is.
3. If I understood correctly, @james-d-mitchell asked if it was possible to show the constructor when documenting a class. I couldn't remember how to do that at the time, but I now recall that is done with something like this:
```rst
.. autoclass:: StaticTransf16
   :class-doc-from: class
   :members:
   :inherited-members:
   :special-members: __init__
```

With the above comments considered, I would be happy to merge

2024-05-23 08:40 UTC, merged