Add pbr for v1
libsemigroups/libsemigroups_pybind11 pull request #191
Opened 2024-09-16 18:07 UTC by Joseph-Edwards

This updates pbr in preparation for v1. Since, in `libsemigroups` there is no "checks" version of multiplying `PBR`s, you can't really do very much with these objects, but they're here nonetheless!

2024-09-16 18:09 UTC, Joseph-Edwards commented
The doc will have some bad signatures until #190 is merged.

2024-09-16 20:03 UTC, james-d-mitchell requested changes

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +Construct from adjacencies 0 to :math:`2n - 1`.
0 should be inside double backticks here

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +    *  would have a point related to a point that is greater than degree();
Reference degree?

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +        [](const PBR& a, size_t b) { return a[b]; },
Is this safe if b is out of bounds?

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +:param x: The identity.
This seems sus

2024-09-16 20:03 UTC, james-d-mitchell commented on tests/test_pbr.py
> +
Maybe add some me tests for the left right constructor?

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +Returns the degree of a :any:`PBR` , where the *degree* of a :any:`PBR` is half
Extra space before comma

2024-09-16 20:03 UTC, james-d-mitchell commented on src/pbr.cpp
> +Construct from adjacencies 1 to :math:`n` and -1 to :math:`-n`.
Mixture of math, plain numbers and double back ticks

2024-09-16 20:05 UTC, james-d-mitchell commented
Can you maybe add the checked multiplication, and the other comparison operators? Shouldn't be much code

2024-09-17 09:06 UTC, Joseph-Edwards commented on src/pbr.cpp
> +    thing.def(py::init<size_t>(),
You could call `product_inplace` and store the results in it? If that's worth anything?

2024-09-17 09:07 UTC, Joseph-Edwards commented
> Can you maybe add the checked multiplication, and the other comparison operators? Shouldn't be much code

Is this simply the case of checking the degrees are the same? Or is there more to it?

2024-09-17 11:49 UTC, james-d-mitchell commented on src/pbr.cpp
> +    thing.def(py::init<size_t>(),
Ah, ok, sounds good

2024-09-17 11:50 UTC, james-d-mitchell commented
> > Can you maybe add the checked multiplication, and the other comparison operators? Shouldn't be much code
> 
> Is this simply the case of checking the degrees are the same? Or is there more to it?

Just checking the degrees are equal and also validating the PBRs, that should do it.

2024-09-24 16:11 UTC, merged