Update froidure-pin-hpp for v1/3
libsemigroups/libsemigroups_pybind11 pull request #197
Opened 2024-10-23 14:48 UTC by james-d-mitchell

2024-11-01 17:43 UTC, james-d-mitchell commented on libsemigroups_pybind11/detail/decorators.py
> +        pass
@Joseph-Edwards the ridiculous fix

2024-11-06 21:03 UTC, Joseph-Edwards requested changes
All looking good to me. Modulo the suggestions outlined below, I'll be happy to merge. Thanks @james-d-mitchell!

2024-11-08 11:49 UTC, james-d-mitchell commented on src/froidure-pin.cpp
> +)pbdoc");
Yup, as discussed.

2024-11-08 12:17 UTC, james-d-mitchell commented on libsemigroups_pybind11/froidure_pin.py
> +# Helpers -- from froidure-pin.cpp
I think I've resolved this, some of the signature should say `FroidurePinBase` and I just got it wrong when I was writing them in this file. Hopefully caught them all!

2024-11-08 14:07 UTC, james-d-mitchell commented
@Joseph-Edwards you happy for me to merge this?

2024-11-08 15:01 UTC, Joseph-Edwards commented
> @Joseph-Edwards you happy for me to merge this?

Yeah looks good to me. Merge away! Thanks @james-d-mitchell!

2024-11-08 16:18 UTC, merged